-- E.anticheat:post_hook(NetworkPeer, "set_synched", function(self, state)
--   if not state then return end
--   E:log("anticheat:", self:id(), "synched")
--   local is_local_peer = self == managers.network:session():local_peer()
--   if is_local_peer then
--     for _,peer in pairs(managers.network:session():peers()) do
--       E.anticheat:check_peer(peer)
--     end
--   else
--     E.anticheat:check_peer(self)
--   end
-- end)
-- E.anticheat:post_hook(NetworkPeer, "set_synched_soft", function(self, state)
--   if not state then return end
--   E:log("anticheat:", self:id(), "synched_soft")
--   local is_local_peer = self == managers.network:session():local_peer()
--   if is_local_peer then
--     for _,peer in pairs(managers.network:session():peers()) do
--       E.anticheat:check_peer(peer)
--     end
--   else
--     E.anticheat:check_peer(self)
--   end
-- end)
